name=input ("enter your name:")
surname=input("enter your surname: ")
age=input("enter your age: ")
fro=input("enter whrere are you from: ")
proffesion=input("what is your proffesion: ")
hobby=input("what is your hobby: ")
print(name + " " + surname + " " + age + " " + fro + " " + proffesion + " " + hobby)
